#!/usr/bin/env python
"""Install the ModAR evaluation shim into an external RoboTwin checkout.

RoboTwin's script/eval_policy.py discovers policies as importable packages under
policy/<NAME>. This writes policy/WAM/{__init__.py, deploy_policy.py,
deploy_policy.yml, eval.sh} so RoboTwin can drive a ModAR checkpoint. The
shim re-exports get_model/eval/reset_model from robotwin_manip.eval.robotwin_deploy,
so the real logic stays version-controlled here. The generated shim records this
checkout's path and permits an explicit MODAR_REPO override. Idempotent; re-run
after moving this checkout or re-cloning RoboTwin.

    python scripts/data/prepare_robotwin.py --robotwin-repo /path/to/RoboTwin
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]

_INIT = '"""RoboTwin policy package: ModAR evaluation shim."""\n'

_DEPLOY_PY = '''"""RoboTwin eval shim for ModAR checkpoints (auto-generated by
scripts/data/prepare_robotwin.py; do not edit here -- edit
robotwin_manip/eval/robotwin_deploy.py in the ModAR repo).

Puts the ModAR repo root on sys.path and re-exports the harness hooks.
"""
import os
import sys

_MODAR = os.environ.get("MODAR_REPO", __MODAR_REPO__)
if _MODAR not in sys.path:
    sys.path.insert(0, _MODAR)

from robotwin_manip.eval.robotwin_deploy import (  # noqa: E402,F401
    eval,
    get_model,
    reset_model,
)
'''

_EVAL_SH = '''#!/bin/bash
# Expert-gated closed-loop eval of a ModAR checkpoint inside RoboTwin.
# For the held-out dyn_val SR sweep (no planner) use
# robotwin_manip/eval/run_sr.py instead.
#
# Usage: bash policy/WAM/eval.sh <task_name> <task_config> <wam_checkpoint> <seed> <gpu_id>
policy_name=WAM
task_name=${1}
task_config=${2}
wam_checkpoint=${3}
seed=${4:-0}
gpu_id=${5:-0}

export CUDA_VISIBLE_DEVICES=${gpu_id}
cd ../..  # RoboTwin root

PYTHONWARNINGS=ignore::UserWarning \\
python script/eval_policy.py --config policy/$policy_name/deploy_policy.yml \\
    --overrides \\
    --task_name ${task_name} \\
    --task_config ${task_config} \\
    --ckpt_setting wam \\
    --seed ${seed} \\
    --policy_name ${policy_name} \\
    --wam_checkpoint ${wam_checkpoint}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--robotwin-repo", required=True)
    args = ap.parse_args()

    repo = Path(args.robotwin_repo)
    if not (repo / "script" / "eval_policy.py").is_file():
        raise SystemExit(f"{repo} does not look like a RoboTwin checkout "
                         "(missing script/eval_policy.py)")
    dst = repo / "policy" / "WAM"
    dst.mkdir(parents=True, exist_ok=True)

    (dst / "__init__.py").write_text(_INIT)
    deploy = _DEPLOY_PY.replace("__MODAR_REPO__", repr(str(_REPO)))
    (dst / "deploy_policy.py").write_text(deploy)
    (dst / "eval.sh").write_text(_EVAL_SH)
    shutil.copyfile(_REPO / "robotwin_manip/eval/deploy_policy.yml",
                    dst / "deploy_policy.yml")

    print(f"installed WAM eval shim -> {dst}")
    for f in ("__init__.py", "deploy_policy.py", "deploy_policy.yml", "eval.sh"):
        print(f"  {f}")


if __name__ == "__main__":
    main()
